spring:
  application:
    name: demo
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/demo_db
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
